[package]
name = "wg-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
nix = { version = "0.30.1", features = ["user"] }
ratatui = "0.29.0"
thiserror = "2.0.17"
zip = { version = "2.2", default-features = false, features = ["deflate"] }
