# name: Publish

# permissions:
#     contents: read

# on:
#     workflow_run:
#         workflows: ["CI"]
#         branches: [main]
#         types: [completed]

# jobs:
#     publish:
#         name: Publish
#         runs-on: ubuntu-latest
#         environment: production
#         steps:
#             - uses: actions/checkout@v4

#             - name: Cache Rust toolchain and dependencies
#               uses: actions/cache@v3
#               with:
#                   path: |
#                       ~/.rustup
#                       ~/.cargo
#                       target
#                   key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

#             - name: Login to crates.io registry
#               uses: actions-rs/cargo@v1
#               with:
#                   command: login
#                   args: ${{ secrets.CRATES_IO_TOKEN }}

#             - name: Publish crate to crates.io
#               uses: actions-rs/cargo@v1
#               with:
#                   command: publish
